### ISSUE TITLE
Comments on Fast Writing with Piano Chords

### ISSUE THREAD

**Issue by nsmarkop** [Sillabix/Michela-steno-keyboard-dictionaries-and-documents#1]
Working through the document, I've found some things that might need to be fixed. Instead of messaging you on Discord constantly, I figured I'd put them here as I go through / find them. Let me know for certain ones if you fix them / how so it can be marked off here.

- [x]  On page 19, a brief for "did" is introduced, SCPi, before "i" is used in a lesson. This is similar to page 20 using it in "unit"'s uian/ipf before it's introduced as well, page 20 using "S" for "SUIT" / "Suiapf", and there may be more.
- [x] On page 19, an example sentence of "an ad of a pan" is used with "ad" being written with "apcs". However, page 16 introduces "apcs" as "add".
- [x] Some of the the examples when introducing sounds, like on page 18 for FP "Napf", don't correspond to actual words. They seem fine for illustrative purposes but showing "Napf" as "gnat" instead of "NAT" could be more useful / practical I think.
- [x] "trade" is introduced as "FPRapcs" on page 18 but on page 19 is used in the example sentence "a trade of pain" as "FPRuapcs".
- [x] "in" is introduced as "N" on page 19 but on the same page is used in the example "a drain in a train" as "Npf" which otherwise was not introduced anywhere.
- [x] "few" is introduced as "FPuia" on page 20. Should that just be "Fuia"? I assumed "FPuia" would be "to" or similar (that's "FPie" though as noted in the appendix).
- [x] "tip" is introduced as "FPin" on page 21 but that should be "tin". "tip" should be "FPip".
- [x] On page 21, "FIan/Sua" is used for "fiancee". In the main English dictionary for Plover, "fiance" is the "base" word, with "fiancee" being the word after a disambiguator ("TPAOE/APB/SA*EU": "fiancee", "TPAOE/APB/SAEU": "fiance" or "TPAOEPB/SA*EU": "fiancee", "TPAOEPB/SAEU": "fiance",). Not that this is wrong, just mentioning it as something different
- [x] It is a bit confusing at times what "~y" is. For example, on page 21 "puppy" is "Pup/Pui" -- so, pup + py. On the same page, "tiny" is "FPui/Ni" -- so, ti + ny. But one is "ui" and one is "i"; why?
- [x] "typed" is written as "FPuip/epcs" on page 21, but should just be "FPuip/pcs".
- [x] You use "not" in the example sentences on page 21 before it or the "ie" sound has been introduced.
- [x] On page 46 you put "a" mapped to "Ua" but in earlier lessons you map it to "ua".
- [x] On page 23, the "long E" sounds section has some briefs that do not use the "ue" for the e sound like "Fepf" for "fete" and "Nepf" for "net".
- [x] "Nuepf" is used in two different briefs on page 23 -- "neet" and "neat". Should the latter not be introduced until "ea" for a disambiguator?
- [x] "treat" is given the brief of "TRuepf" on page 23 but that should be "FP" for the "T" in the brief.
- [x] "pro" is given the brief of "PRuie" on page 23 but that comes before the introduction of "uie" on page 24. Should it be "PRie" or should it appear later?
- [x] "potato" on page 24 has the brief of "Puie/PFuafp" but the P and F should be swapped in the second stroke to match steno order.
- [x] "nodded" is given the brief of "Nuiepcs/pcs" on page 24. Should "nod" not be "Niepcs" with nodded being "Niepcs/pcs"? "node" + "ed" isn't a word that I'm aware of.
- [x] "cow" is introduced as "CPia" on page 24 but "CP" hasn't been introduced at this point yet. Same with "cast" and "crest".
- [x] "had" is introduced as "FCancs" on page 24 but shouldn't it be "FCapcs"?
- [x] All of the briefs on page 25 have "FCR" in the wrong order as "CFR".
- [x] "strand" on page 25 is given the brief of "FCRanf" but "nf" as the "nd" ending hasn't been introduced at that point yet (I assumed it was incorrect and you were supposed to do "FCRanpcs" with a tucked thumb until I looked further). Same for "ns" for "ing" as used in "string", "ps" for "ch" as used in "stretch", and "pc" being "k" as used in "strike" not being introduced yet.
- [x] "CP" and "C" for "c" and "sh" in the briefs on page 25 haven't been introduced at that time yet.
- [x] The title of Lesson V is still in Italian (some other parts are too across the document, I'm assuming it's known already!)
- [x] "to", "Dan", "ate", and "and" are used in the sentences on page 26 but haven't been introduced yet.

... And that's it for what I'm through right now.

**Comment by Sillabix** [comment]
Wow, thanks. I'll fix it and let you know.

**Comment by Sillabix** [comment]
I've done all the corrections and uploaded a new file (ver. 1.1)

**Comment by Sillabix** [comment]
I close this issue. If you have other comments, please leave them on file 1.1
